config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/users', to: 'users#index', as: 'users'

  get 'dashboard/users/add', to: 'users#new', as: '/users/add'
  post 'dashboard/users', to: 'users#create'

  get 'dashboard/users/:id/edit', to: 'users#edit', as: '/users/edit'
  patch 'dashboard/users/:id', to: 'users#update'
  put 'dashboard/users/:id', to: 'users#update'
  #
  delete 'dashboard/users/:id', to: 'users#destroy', as: '/user'
  get 'dashboard/users/:id/profile', to: 'users#show', as:'/users/profile'
  # resources :users, only: [:new, :create]

  # get 'cafe/index'
  root 'cafe#index'

  get 'cafe/about'

  get 'dashboard', to: "dashboard#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :avatar, AvatarUploader
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { minimum: 6, maximum: 255 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :phone, length: {maximum: 14, minimum: 10}, allow_nil: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 255 }, allow_nil: true
  enum status: {Owner: 0, Admin: 1, Employee: 2}
  enum gender: {Male: 0, Female: 1, Not_sure: 2}

  validates_processing_of :avatar
  validate :avatar_size_validation

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Return a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User,new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private
    def avatar_size_validation
      errors[:avatar] << "Should be less than 5MB" if avatar.size > 5.megabytes
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
    @user = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'dashboard'
  add_breadcrumb "Dashboard", :dashboard_path
  add_breadcrumb "User", '#'

  def index
    @user = User.all
  end

  def new
    add_breadcrumb "Add User", '#'
    @user = User.new
  end

  def edit
    add_breadcrumb "Edit User", '#'
    @user = User.friendly.find(params[:id])
  end

  def show
    add_breadcrumb "Profile", '#'
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile info was updated"
      redirect_to users_profile_url
    else
      render 'edit'
    end
  end

  def destroy
    User.friendly.find(params[:id]).destroy
    flash[:danger] = "User has been deleted"
    redirect_to users_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Congratulations! add user has been success. "
      redirect_to users_url
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone, :status, :gender, :password, :password_confirmation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Dashboard"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end

  def default_keyword(page_keyword = '')
    base_keyword = "Royal Cokelat Cafe"
    if page_keyword.empty?
      base_keyword
    else
      base_keyword + ", " + page_keyword
    end
  end

  def default_description(page_description = '')
    page_description = "Royal Cokelat Cafe Pelopor Milkshake"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cafe/about.html.erb
<h1>Cafe#about</h1>
<p>Find me in app/views/cafe/about.html.erb</p>

app/views/cafe/index.html.erb
<h1>Cafe#index</h1>
<p>Find me in app/views/cafe/index.html.erb</p>

app/views/dashboard/index.html.erb
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Dashboard
      <small>Panel Management</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- <h1>Dashboard#index</h1>
    <p>Find me in app/views/dashboard/index.html.erb</p> -->
    <!-- Your Page Content Here -->

    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3><%= @user.count %></h3>

            <p>User Available</p>
          </div>
          <div class="icon">
            <i class="ion ion-person-stalker"></i>
          </div>
          <%= link_to 'View All User <i class="fa fa-arrow-circle-right"></i>'.html_safe, users_path, class: "small-box-footer" %>
          <!-- <a href="#" class="small-box-footer">View All User <i class="fa fa-arrow-circle-right"></i></a> -->
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3>53<sup style="font-size: 20px">%</sup></h3>

            <p>Event Specials</p>
          </div>
          <div class="icon">
            <i class="ion ion-calendar"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
          <div class="inner">
            <h3>44</h3>

            <p>Promo Code</p>
          </div>
          <div class="icon">
            <i class="ion ion-easel"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
          <div class="inner">
            <h3>65</h3>

            <p>Unique Visitors</p>
          </div>
          <div class="icon">
            <i class="ion ion-pie-graph"></i>
          </div>
          <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
    </div>

  </section>
  <!-- /.content -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= render 'layouts/dashboard/head' %>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">
        <%= render 'layouts/dashboard/nav' %>
        <%= render 'layouts/dashboard/left-sidebar' %>
        <%= yield %>
        <%= render 'layouts/dashboard/footer' %>
        <div class="control-sidebar-bg"></div>
    </div>
  </body>


</html>

app/views/layouts/dashboard/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    Royal Cokelat Cafe
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2016 <a href="#">Royal Cokelat</a>.</strong> All rights reserved.
</footer>

app/views/layouts/dashboard/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<meta name="keywords" content="<%= default_keyword(yield(:keyword)) %>"/>
<meta name="description" content="<%= default_description(yield(:description))%>"/>

app/views/layouts/dashboard/_left-sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <!-- <div class="user-panel">
      <div class="pull-left image">
        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Alexander Pierce</p>
        Status
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div> -->

    <!-- search form (Optional) -->
    <!-- <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form> -->
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Main Navigation</li>
      <!-- Optionally, you can add icons to the links -->
      <li class="active"><%= link_to "<i class=\"fa fa-dashboard\"></i> <span>Dashboard</span></a>".html_safe, dashboard_url %>
        <!-- <a href="#"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a> -->
      </li>
      <!-- <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li> -->
      <li class="treeview active">
        <a href="#">
          <i class="fa fa-list-alt"></i>
          <span>Menu</span>
          <span class="pull-right-container">
            <i class="pull-right fa fa-angle-left "></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-coffee"></i><span>Drinks</span></a></li>
          <li><a href="#"><i class="fa fa-cutlery"></i><span> Foods</span></a></li>
          <li><a href="#"><i class="fa fa-cubes"></i><span> Specials</span></a></li>
        </ul>
      </li>
      <li><a href="#"><i class="fa fa-ticket"></i> <span>Promo</span></a></li>
      <li><a href="#"><i class="fa fa-calendar"></i> <span>Event</span></a></li>
      <li><a href="#"><i class="fa fa-file-text"></i> <span>Blog</span></a></li>
      <li><a href="#"><i class="fa fa-picture-o"></i> <span>Gallery</span></a></li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-cogs"></i>
          <span>Setting</span>
          <span class="pull-right-container">
            <i class="pull-right fa fa-angle-left "></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><%= link_to "<i class=\"fa fa-user\"></i><span>User</span>".html_safe, users_url %></li>
          <li><a href="#"><i class="fa fa-building"></i><span>Branch</span></a></li>
          <li><a href="#"><i class="fa fa-database"></i><span>Others</span></a></li>
        </ul>
      </li>
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/dashboard/_nav.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <%= link_to '<span class="logo-mini"><b>R</b>|C</span><span class="logo-lg"><b>Royal</b>Cokelat</span>'.html_safe, dashboard_path, class: "logo" %>

  <!-- <a href="" class="logo"> -->
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <!-- <span class="logo-mini"><b>R</b>|C</span> -->
    <!-- logo for regular state and mobile devices -->
    <!-- <span class="logo-lg"><b>Royal</b>Cokelat</span> -->
  <!-- </a> -->

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the messages -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <!-- User Image -->
                      <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"> -->
                    </div>
                    <!-- Message title and timestamp -->
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <!-- end message -->
              </ul>
              <!-- /.menu -->
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <li><!-- start notification -->
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image"> -->

              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <!-- <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li> -->
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul style="margin: 0px 20px; padding-bottom:25px;">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for (@user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="box-body">
    <div class="form-group col-md-6">
      <%= f.label :full_name %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_field :name, class: "form-control", placeholder: "Full Name" %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :email_address %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        <%= f.email_field :email, class: "form-control", placeholder: "Email Address" %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :status %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-book"></i></span>
        <%= f.select :status, User.statuses.keys, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :gender %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-genderless"></i></span>
        <%= f.select :gender, User.genders.keys, {}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :password %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-key"></i></span>
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :password_confirmation %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-key"></i></span>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
      </div>
    </div>
    <!-- <div class="form-group col-md-6">
      <label for="exampleInputFile">File input</label>
      <input type="file" id="exampleInputFile">

      <p class="help-block">Example block-level help text here.</p>
    </div> -->

    <div class="form-group col-md-6">
      <%= f.label :phone %><span style="color: red;">*</span>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-phone"></i></span>
          <%= f.text_field :phone, class:"form-control", autofocus:true, placeholder:'without +62 or 0', value: number_to_phone('')%>
      </div>
      <!-- /.input group -->
    </div>
  </div>
  <!-- /.box-body -->

  <div class="box-footer">
    <p class="help-block">NB :<br/><span style="color: red;">*</span> Required field</p>
    <%= f.submit yield(:button), class: "btn btn-primary pull-right" %>
    <!-- <button type="submit" class="btn btn-primary pull-right">Submit</button> -->
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<%= provide(:button, "Edit Profile") %>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      User Management |
      <small>Edit User</small>
    </h1>
    <ol class="breadcrumb">
      <%= link_to "<i class='fa fa-dashboard'></i> ".html_safe + render_breadcrumbs %>
      <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li> -->
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- <h1>Users#new</h1>
    <p>Find me in app/views/users/new.html.erb</p> -->

    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Form User</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <!-- <form role="form"> -->
          <%= render 'users/form' %>
          <!-- </form> -->
        </div>
        <!-- /.box -->
      </div>
      <div class="clearfix"></div>
      <!--/.col (left) -->
    </div>

  <!-- Your Page Content Here -->

  </section>
  <!-- /.content -->
</div>

app/views/users/index.html.erb
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      User Management | <small> Add, Delete, Edit</small>
    </h1>
    <ol class="breadcrumb">
      <%= link_to "<i class='fa fa-dashboard'></i> ".html_safe + render_breadcrumbs %>
      <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li> -->
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- <h1>Users#index</h1>
    <p>Find me in app/views/users/index.html.erb</p> -->
    <!-- Your Page Content Here -->


    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">All User of Royal Cokelat</h3>
            <%= link_to "Add User", users_add_path, class: "btn btn-success btn-sm pull-right", style: "margin-right: 30px;" %>

          </div>
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <!-- /.box-header -->
          <div class="box-body">

            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
                <% @user.each do |users| %>
              <tr>
                <td><%= users.name %></td>
                <td><%= users.email %></td>
                <td><%= number_to_phone(users.phone, country_code: 62, delimiter: "-")%></td>
                <td>
                  <%= link_to "Edit User", users_edit_url(users), class: "btn btn-info btn-xs", method: :get %>
                  <%= link_to "Delete", users, class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure to delete this user?"} %>
                </td>
              </tr>
               <% end %>
              </tbody>
              <tfoot>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Action</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>


  </section>
  <!-- /.content -->
</div>

<script>
  $(function () {
    $("#example1").dataTable();
    $('#example2').dataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true
    });
  });
</script>

app/views/users/new.html.erb
<%= provide(:title, "Add User") %>
<%= provide(:button, "Add User") %>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      User Management |
      <small>Add User</small>
    </h1>
    <ol class="breadcrumb">
      <%= link_to "<i class='fa fa-dashboard'></i> ".html_safe + render_breadcrumbs %>
      <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li> -->
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- <h1>Users#new</h1>
    <p>Find me in app/views/users/new.html.erb</p> -->

    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Form User</h3>
          </div>
          <!-- /.box-header -->
          <!-- form start -->
          <!-- <form role="form"> -->
          <%= render 'users/form' %>
          <!-- </form> -->
        </div>
        <!-- /.box -->
      </div>
      <div class="clearfix"></div>
      <!--/.col (left) -->
    </div>

  <!-- Your Page Content Here -->

  </section>
  <!-- /.content -->
</div>